config/routes.rb
require 'resque/server'

Humblesuggestions::Application.routes.draw do
  mount Resque::Server, :at => "/admin/queues"

  resources :suggestions

  devise_for :users, :controllers => {:registrations => "registrations"}

  root :to => 'welcome#index'
  match '/home' => 'welcome#home'
  match '/settings' => 'welcome#settings'
  match '/auth/:provider/callback', to: 'sessions#create'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_user!, except: :index

  def index
    if current_user
      redirect_to '/home'
    else
      @track = 'Home Page Visit'
    end
  end

  def home
    @track = 'User Home Visit'
  end

  def settings
    if current_user.connected?
      @track = 'Settings Visited'
    else
      @track = 'Settings Reached'
    end
  end
end

app/views/welcome/home.html.erb
<div id="email">

  <h1>Some ideas for your day</h1>
  <p>
    Your feedback is really important to us and improves our suggestions.
  </p>

  <div id="intense" class="day">
    <div class="day-header">
      An active day...
    </div>
    <div class="day-box">
      <div class="day-item">
        <div class="day-suggestion">
          Go for a run
        </div>
        <div class="day-timing">
          Morning
        </div>
      </div>
      <div class="day-item">
        <div class="day-suggestion">
          Breakfast
        </div>
        <div class="day-timing">
          Morning
        </div>
      </div>
      <div class="day-item">
        <div class="day-suggestion">
          Call friends and family
        </div>
        <div class="day-timing">
          Late Morning
        </div>
      </div>
      <div class="day-item">
        <div class="day-suggestion">
          Week&apos' Grocery Shopping then Tidying Up
        </div>
        <div class="day-timing">
          Noon
        </div>
      </div>
      <div class="day-item">
        <div class="day-suggestion">
          Play Tennis
        </div>
        <div class="day-timing">
          Afternoon
        </div>
      </div>
      <div class="day-item">
        <div class="day-suggestion">
          Brunch
        </div>
        <div class="day-timing">
          Late Afternoon (3ish)
        </div>
      </div>
      <div class="day-item">
        <div class="day-suggestion">
          A casual outdoor activity: ...
        </div>
        <div class="day-timing">
          Evening
        </div>
      </div>
      <div class="day-item">
        <div class="day-suggestion">
          Practice your hobby
        </div>
        <div class="day-timing">
          Late Evening
        </div>
      </div>
      <div class="day-item">
        <div class="day-suggestion">
          Dinner
        </div>
        <div class="day-timing">
          Night
        </div>
      </div>
      <div class="day-item">
        <div class="day-suggestion">
          Write a letter
        </div>
        <div class="day-timing">
          Night
        </div>
      </div>
      <div class="day-item">
        <div class="day-suggestion">
          Read and pass out!
        </div>
        <div class="day-timing">
          Night
        </div>
      </div>
    </div>
    <div class="day-feedback">
      <div class="day-feedback-bad">
        Ehh.. subpar jeeves. Try again.
      </div>
      <div class="day-feedback-good">
        Smashing idea!
      </div>
    </div>
  </div>

</div>

app/views/welcome/home.html.haml
.grid-100.section#question
  %span{:style => 'float:left;'} I have   
  %ul#time
    %li.choice{"data-choice-type" => "time", "data-choice" => "5"} a few minutes
    %li.choice{"data-choice-type" => "time", "data-choice" => "15"} roughly 15 minutes
    %li.choice{"data-choice-type" => "time", "data-choice" => "30"} around half an hour
    %li.choice{"data-choice-type" => "time", "data-choice" => "60"} around an hour
    %li.choice{"data-choice-type" => "time", "data-choice" => "180"} 2-3 hours
  %span{:style => 'float:left;'} and I am 
  %ul#location
    %li.choice{"data-choice-type" => "location", "data-choice" => "home"} at home.
    %li.choice{"data-choice-type" => "location", "data-choice" => "work"} taking a break.
    %li.choice{"data-choice-type" => "location", "data-choice" => "work"} working.

#suggestions

app/views/welcome/index.html.haml
.grid-50.mobile-grid-100#intro
  %h2 Welcome
  %p.teaser
    %span{:class => 'deep'} Too much content not enough time?
    %br
    %br
    Read, watch, and, listen on your own time.
    %br
    We connect your lists, todos, and subscriptions from services you already use across the web and help you make the most of your time with a daily suggestion email.

.grid-50.mobile-grid-100#signup
  %h2 Join us

  = form_for(resource, :url => registration_path(resource)) do |f| 
    - if resource.errors.messages.has_key?(:email)
      %p.error
        There was a problem with your email address. Please make sure it entered properly and that you have not already registered.
    - if resource.errors.messages.has_key?(:signup_code)
      %p.error
        You need to use a valid signup code until registration is open to the public.
        %br
        <a href='mailto:me@kunalashah.com'>Ask me for one</a>.
    - if resource.errors.messages.has_key?(:password)
      %p.error
        Please enter a valid password and try again.
    %fieldset
      = f.email_field :email, :id => 'new_email', :placeholder => 'enter your email to get started or...'
    %fieldset
      = f.password_field :password, :id => 'new_password', :placeholder => 'enter a password'
    %fieldset
      = f.text_field :signup_code, :id => 'new_signup_code', :placeholder => 'sign up code'
      = f.submit :value => "Join", :class => 'btn btn-primary btn-large'

  %br
  %h3 Already humbled? Sign in
  = form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f|
    %fieldset
      = f.email_field :email, :id => 'email', :placeholder => 'enter your email'
    %fieldset
      = f.password_field :password, :id => 'password', :placeholder => 'enter your password'
      = f.submit :value => "Sign In", :class => 'btn btn-large'
    %fieldset
      = link_to "Forgot your password?", new_password_path(resource_name)

app/views/welcome/settings.html.haml
.grid-100.mobile-grid-100.section#connect
  %h2 Connect Services
  %p.teaser
    %span{:class => 'deep'} Connect the services you&apos;re using below. We do not share your information with anyone in anyway.

.section#service-options.grid-100.mobile-grid-100
  .service-option
    - if !current_user.instapaper_connected?
      %h3= link_to 'Instapaper', '/auth/instapaper'
      (click to connect)
    - else
      %h3 Instapaper
      (currently connected)
  .service-option
    - if !current_user.netflix_connected? 
      %h3= link_to 'Netflix', '/auth/netflix'
      (click to connect)
    - else
      %h3 Netflix
      (currently connected)

.section.grid-100.mobile-grid-100
  Not seeing a service you were looking for?
  %br
  <a href="mailto:me@kunalashah.com">Contact me</a> and I may add it.

- unless params[:initial]
  .section.grid-100.mobile-grid-100
    %h2 Account
    = link_to 'Click here to logout', destroy_user_session_path, :class => 'deep', :method => :delete
    = form_for(current_user, :as => :user, :url => registration_path(current_user), :html => { :method => :put }) do |f|
      = devise_error_messages!

      %fieldset
        = f.label :email
        %br
        = f.email_field :email
      %fieldset
        = f.label :password
        %br
        %i (leave blank if you don't want to change it)
        %br
        = f.password_field :password, :autocomplete => "off"
      %fieldset
        = f.label :password_confirmation
        %br
        = f.password_field :password_confirmation
      %fieldset
        = f.label :current_password
        %br
        %i (we need your current password to confirm your changes)
        %br
        = f.password_field :current_password
      %fieldset
        = f.submit "Update", :class => 'btn btn-large btn-primary'

= "<script>mixpanel.alias('#{current_user.id}');</script>".html_safe